#cloud-config
users:
  - name: yc-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - ${join("\n", ssh_keys)}

packages:
  - nginx

runcmd:
  - systemctl enable nginx
  - systemctl start nginx